name: ci

on:
  - workflow_dispatch

env:
  COLUMNS: 150
  UV_PYTHON: 3.13

jobs:

  build:
    name: build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.interpreter || 'all' }}${{ matrix.os == 'linux' && format(' - {0}', matrix.manylinux == 'auto' && 'manylinux' || matrix.manylinux) || '' }})
    # only run on push to main and on release
    strategy:
      fail-fast: false
      matrix:
        os: [windows]
        target: [undefined]
        include:
          # windows;
          # x86_64 pypy builds are not PGO optimized
          # i686 not supported by pypy
          # windows 11 arm supports 3.11 and up, not PGO optimized for now
          - os: windows
            target: x86_64
            interpreter: 3.12

        exclude:
          # was just a dummy variable to set a default value for target
          - target: undefined

    runs-on: ${{ matrix.runs-on || format('{0}-latest', (matrix.os == 'linux' && 'ubuntu') || matrix.os) }}
    steps:
      - uses: actions/checkout@v5

      - name: set up python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          architecture: ${{ matrix.python-architecture || 'x64' }}

      - run: pip install -U twine 'ruff==0.5.0' typing_extensions

      - name: build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64-pc-windows-msvc
          args: --release -Z build-std --target x86_64-win7-windows-msvc --out dist --interpreter ${{ matrix.interpreter || '3.9 3.10 3.11 3.12 3.13 3.14 3.14t pypy3.10 pypy3.11' }}
          rust-toolchain: nightly
          rustup-components: rust-src
          docker-options: -e CI

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} dist/

      - run: twine check --strict dist/*

      - uses: actions/upload-artifact@v5
        with:
          name: pypi_files_${{ matrix.os }}_${{ matrix.target }}_${{ matrix.interpreter || 'all' }}_${{ matrix.manylinux }}
          path: dist
